### ISSUE TITLE
poco errors

### ISSUE THREAD

**Issue by hardjob** [arturoc/ofxHttpUtils#16]
i tied to compile an app which use ofxHttpUtils , but i got this error addons/ofxHttpUtils/src/ofxHttpUtils.h:18:50: fatal error: Poco/Mutex.h...

i'm using the current openframeworks-master version

**Comment by arturoc** [comment]
since next version poco has been moved to an addon so in order to use any addon that depends on it you also need to include ofxPoco in your project

**Comment by hardjob** [comment]
how can i include the addon ?
should I include the full path of the headers , exple #include "ofxPoco/libs/poco/include/Poco/Mutex.h" or what

**Comment by arturoc** [comment]
using the project generator to generate your project is the easiest, there you can chooses which addons to include
